version: "3.9"
services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "83:80"
    deploy:
      replicas: 3
    networks:
      - npm_public

networks:
  npm_public:
    external: true
